[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "5b0fbf0df120a405fe8b52b9bad394dd02ffbb4e"
julia_version = "1.11"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "51ebe7942b46aa1254993235cea6f8f430a199bd537d5edbf8c4fd1ee5ae959b"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.5+0/libmousetrap.v0.4.5.x86_64-w64-mingw32-julia_version+1.11.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "4f8067cc8e286a2c5bbc4ff361c73ed35376d64c"
julia_version = "1.10"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "4bab4d2d63ecd7098a0867c9c8895584ea39191ae670487d251ebd072b8ba3f4"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.5+0/libmousetrap.v0.4.5.x86_64-w64-mingw32-julia_version+1.10.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "f4a09967807451502c6964240e82ff2b21105ea5"
julia_version = "1.10"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "04de57c88929d3454764f1987c3e99e864da4cb1bba83c0fcf5e1b7af44e69cf"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.6+0/libmousetrap.v0.4.6.x86_64-w64-mingw32-julia_version+1.10.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "0cd9c5c4d30ac55e08a3307c5e98fc83b6a79109"
julia_version = "1.10"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "336e6e9eff71b89339bd7d0504c2f77f04719018444e800d7bc62d3832de5737"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.6+0/libmousetrap.v0.4.6.x86_64-w64-mingw32-julia_version+1.10.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "594a7f432b5bac1fd868429b77a88bb141f9c0a4"
julia_version = "1.10"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "553c9f256a3cf3c8accdb9a85c971066ce71021187b8cef228ec192c7d27537c"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.7+0/libmousetrap.v0.4.7.x86_64-w64-mingw32-julia_version+1.10.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "24fb2444c1697a8dfcee8ebdfa093f754b1e8747"
julia_version = "1.10"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "83584ffc8bfae40a960633880053c8e93b3238a8a3d20a170e8f076db4a5f078"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.7+0/libmousetrap.v0.4.7.x86_64-w64-mingw32-julia_version+1.10.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "3e41bea5dc2e6f571b7e1210ca9111fabeafefd0"
julia_version = "1.10"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "4e503b71087662841db407425db640fc1ef3f7ac431e8a3beecceab95cea07d7"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.7+0/libmousetrap.v0.4.7.x86_64-w64-mingw32-julia_version+1.10.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "aba771890cdb3fd4d80f5cc5b894161b4a306d69"
julia_version = "1.10"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "f538b1ab20b8c316abd45f28fde3fc2375aba069989c6417c32e61e383eeb052"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.8+0/libmousetrap.v0.4.8.x86_64-w64-mingw32-julia_version+1.10.tar.gz"
[[libmousetrap]]
arch = "x86_64"
git-tree-sha1 = "d44da5259b9868fa61775568b98988abb63cd5a6"
julia_version = "1.10"
os = "windows"

    [[libmousetrap.download]]
    sha256 = "396ae506a137e35af60aecefd757a67f245174a6465ccdc2e1b782258272d580"
    url = "https://github.com/HyperSphereStudio/libmousetrap_jll/releases/download/libmousetrap-v0.4.8+0/libmousetrap.v0.4.8.x86_64-w64-mingw32-julia_version+1.10.tar.gz"
